version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: docker-backend-app
    restart: always
    working_dir: /var/www/
    volumes:
     - ../app:/var/www
     - ./conf/php/php.ini:/usr/local/etc/php/php.ini
  nginx:
    image: nginx:1.22.0-alpine
    container_name: docker-backend-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../app:/var/www
      - ./conf/nginx/log:/var/log/nginx
      - ./conf/nginx/conf.d:/etc/nginx/conf.d